#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima_ihrm?useUnicode=true&characterEncoding=utf8
    username: jfinal
    password: jfinal
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
# JWT的相关配置
jwt:
  config:
    key: saas-ihrm
    ttl: 3600000